language: clojure
cache:
  directories:
  - $HOME/.m2
script: lein test
jdk:
- openjdk7
- oraclejdk7
- oraclejdk8
before_deploy: lein codox
deploy:
- provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: target/doc
  on:
    branch: master
    jdk: oraclejdk8
- provider: script
  script: lein deploy clojars
  skip_cleanup: true
  on:
    branch: master
    jdk: oraclejdk8
branches:
  only:
  - master
env:
  global:
  - secure: RShYPLv/mdht4NYg826mEMJHx4rykdkDUUmTWSGvieGlGjOXpwRurxHlEzcxNa0euBCo9jIams4KwnZH7qrxxlisuffPpJzjv6gp1dTcP839dSG554qSBkCU4aoBdV0joz4+Olj6z2bKybzzpKPvLSjjDCR0oH2+pLbzPVyId+wobbxxfpDRS/cIhOno/A2/ennG4CwcsMnl7g/d9DEipJ69/0Nu/QbTle5gebHT0skJWxBeXcKVyshU4lGgq2JmqYSdKdVdt1MrXy1LD8hlFoWzsS3DP9yj4H6G7YvGLogmXmR9qhlKRla2vURMxxAn47uydUeYHNxM5qoydBi2QXAlNv1Qfl9ILmFk7tdnfOgAjjzTNFkaYYtx5ReEgUG6b403lX3udmJLwPtXDrYNk/q29NzCCKpm8R5PXXD+YyAYdbPz+uPvBeiDvPViyCTI2s1T3y4aCv1wAFjsIc8epTu7g/sRsqAamAwdbRLfWrZb+OR5VdQQ+ibSAov+iwrAm4bGdGbFUkdreSPr1yEJ5tQfq9ioz8y5UQTEeDFVDXUGvwb720fMx7AfNv4gD/rEqofwrHsAfLTdqjxvS5KRiC/X/tuat3I7PruI4g0QrmD/N6Gvat1dxPAbCjnCMqtIHVch8e3Jg/pIvHp2uEPljn1HsFjpITeeHqtZVuu/OnI=
  - secure: G5Cs5qInPfT8VRA6nZVsqi59Zx7WeQzBdngcgwpLjJTMsUDJcAeqQOvgWkyKOvOxPIghokFnD6//3lISlsxbZdzXjyJBqsLlwm60ThLQCcC8wi07Q+lwVWx7C0sGwNSqF75oI97gFtx+hhoqtvlReuAu+j32pCvJyfglecL8leGLpk1p+/d7o4ny1msrOStc8rDRny1um/Z27SBJY+BlUUFEsQ6p9XbSYcgcVOdztZXS9ABRaIVGUUsQ5gHcezQ6C2jvDfoQmD+eIaAlgSRUotixdyGSI754NECjkco+RnDX63lk5+WlQiSQoNjS+wNQ+jUs4hAcZeY2OCdx5uzxwmCS/5qC05VLGpu8od1D/0tW1wVCdJXR+bQ3F396C42Q6Svt7ZK0DGWbkqadWiHEyaQRcbjZIaEIxjjZ39jwoUwDANghBMjURFuuR1nTwmvjIxzOIecM6wI1LJm5JkbiroXYNAG+wxqa5xBDVdGg16Nt6yS+FISjQ8Fo3tS5JMurJVbhYexWHGX9DEoetOXDILJrdcsYuAsncpOlg0raUL2rOwnPAey+EWGP7f0fJ47BeyE3zItkkmKjIyY2Usd3GTbJMvgwbmh/z3syGkixZKD/zTgCXcGaFyxfMKgnA5tEvWRXmspcBpHF+pfqehg9au6pz3PrfdXQZisJb/uSLi0=
  - secure: kPTUwF+nHMGehqnFb/WDx1Q+KL1qhRREXVjG7Y54yLgWVCfAIif055t2+PQVwBXZG6McMxl8SuYGPfrO77zYarkmw/3zooFFiUSq3WjtuE5N5hZtOhnkyIkTpbE3gV4dc6IMKRA3WfmniihSSZZSzSq4vCBW51bAU/ff0WASAW1NsNwDpj6/oFygIA/IexU+77VJjq+SAuhczjg7/4QMPWPu5Gc4ZL6ykAMimDuYND+j4RJLo8JEgtD6s06vTnuU+xrJtb825WDCcajnnH517aDPsExLhVEBLlaH6Wm+EfM6BQJ3tNwh5GKI99uJHdeeJpotcnM1OOspW9A+Nh1r0owkeuXve+AiZBntqEW0ivzmB+d/zxb3vPmyGSMfso/f/xWiFSZyKKnI1872xUOuFe0/F+FmuOKn2ZEPFSrDg4yEwM3XpYh6la1oHRAL3QzgBtwsMCh/7LXPmRP+8XEK0CBhE1yXmB/ea/KsfFAOIIxXO9g3aAfoXk+JKFl3FE9ZdBiMbzYC4WzftJKi1kRNKX6N3f0NvtAelQroW4/dkvOUtdACoL+QqSrJcVM3VtOq+83Sq2T2BYTulajaXqg/kXU0m+snvFGolrDS51o+0oUXCg2i2b6PVFkpWjE9NZ03NXSO8+1hRp1Iq4dxbh4NCHqhf1n7xCjYVd3VcUcksBs=
